module.exports = {
  up: async ({ context: queryInterface }) => {
    await queryInterface.bulkInsert('games', [
      {
        date: '2014-02-15',
        home_team_id: 1,
        away_team_id: 6,
        result: '5-3',
        home_goal: 5,
        away_goal: 3,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '2-1',
        halftime_home_goal: 2,
        halftime_away_goal: 1,
      },
      {
        date: '2014-02-15',
        home_team_id: 8,
        away_team_id: 13,
        result: '11-7',
        home_goal: 11,
        away_goal: 7,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '7-3',
        halftime_home_goal: 7,
        halftime_away_goal: 3,
      },
      {
        date: '2014-02-16',
        home_team_id: 2,
        away_team_id: 12,
        result: '4-2',
        home_goal: 4,
        away_goal: 2,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '1-2',
        halftime_home_goal: 1,
        halftime_away_goal: 2,
      },
      {
        date: '2014-02-16',
        home_team_id: 5,
        away_team_id: 9,
        result: '3-9',
        home_goal: 3,
        away_goal: 9,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '0-2',
        halftime_home_goal: 0,
        halftime_away_goal: 2,
      },
      {
        date: '2014-02-17',
        home_team_id: 6,
        away_team_id: 1,
        result: '4-6',
        home_goal: 4,
        away_goal: 6,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '0-3',
        halftime_home_goal: 0,
        halftime_away_goal: 3,
      },
      {
        date: '2014-02-17',
        home_team_id: 13,
        away_team_id: 8,
        result: '6-5',
        home_goal: 6,
        away_goal: 5,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '1-1',
        halftime_home_goal: 1,
        halftime_away_goal: 1,
      },
      {
        date: '2014-02-18',
        home_team_id: 12,
        away_team_id: 2,
        result: '3-5',
        home_goal: 3,
        away_goal: 5,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '1-1',
        halftime_home_goal: 1,
        halftime_away_goal: 1,
      },
      {
        date: '2014-02-18',
        home_team_id: 9,
        away_team_id: 5,
        result: '5-3',
        home_goal: 5,
        away_goal: 3,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '2-1',
        halftime_home_goal: 2,
        halftime_away_goal: 1,
      },
      {
        date: '2014-02-20',
        home_team_id: 1,
        away_team_id: 6,
        result: '7-4',
        home_goal: 7,
        away_goal: 4,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '3-2',
        halftime_home_goal: 3,
        halftime_away_goal: 2,
      },
      {
        date: '2014-02-20',
        home_team_id: 8,
        away_team_id: 13,
        result: '11-2',
        home_goal: 11,
        away_goal: 2,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '6-1',
        halftime_home_goal: 6,
        halftime_away_goal: 1,
      },
      {
        date: '2014-02-21',
        home_team_id: 2,
        away_team_id: 12,
        result: '6-2',
        home_goal: 6,
        away_goal: 2,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '2-1',
        halftime_home_goal: 2,
        halftime_away_goal: 1,
      },
      {
        date: '2014-02-21',
        home_team_id: 5,
        away_team_id: 9,
        result: '9-5',
        home_goal: 9,
        away_goal: 5,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '4-4',
        halftime_home_goal: 4,
        halftime_away_goal: 4,
      },
      {
        date: '2014-02-22',
        home_team_id: 6,
        away_team_id: 1,
        result: '0-0',
        home_goal: 0,
        away_goal: 0,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '0-0',
        halftime_home_goal: 0,
        halftime_away_goal: 0,
      },
      {
        date: '2014-02-22',
        home_team_id: 13,
        away_team_id: 8,
        result: '5-4',
        home_goal: 5,
        away_goal: 4,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '2-2',
        halftime_home_goal: 2,
        halftime_away_goal: 2,
      },
      {
        date: '2014-02-23',
        home_team_id: 12,
        away_team_id: 2,
        result: '0-0',
        home_goal: 0,
        away_goal: 0,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '0-0',
        halftime_home_goal: 0,
        halftime_away_goal: 0,
      },
      {
        date: '2014-02-23',
        home_team_id: 9,
        away_team_id: 5,
        result: '3-7',
        home_goal: 3,
        away_goal: 7,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '2-2',
        halftime_home_goal: 2,
        halftime_away_goal: 2,
      },
      {
        date: '2014-02-25',
        home_team_id: 1,
        away_team_id: 6,
        result: '0-0',
        home_goal: 0,
        away_goal: 0,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '0-0',
        halftime_home_goal: 0,
        halftime_away_goal: 0,
      },
      {
        date: '2014-02-25',
        home_team_id: 2,
        away_team_id: 12,
        result: '0-0',
        home_goal: 0,
        away_goal: 0,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '0-0',
        halftime_home_goal: 0,
        halftime_away_goal: 0,
      },
      {
        date: '2014-02-25',
        home_team_id: 5,
        away_team_id: 9,
        result: '7-2',
        home_goal: 7,
        away_goal: 2,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '3-0',
        halftime_home_goal: 3,
        halftime_away_goal: 0,
      },
      {
        date: '2014-02-25',
        home_team_id: 8,
        away_team_id: 13,
        result: '5-2',
        home_goal: 5,
        away_goal: 2,
        season_id: 108,
        category: 'quarter',
        group: 'Q1',
        playoff: true,
        halftime_result: '1-2',
        halftime_home_goal: 1,
        halftime_away_goal: 2,
      },
      {
        date: '2014-03-01',
        home_team_id: 2,
        away_team_id: 5,
        result: '3-6',
        home_goal: 3,
        away_goal: 6,
        season_id: 108,
        category: 'semi',
        group: 'S1',
        playoff: true,
        halftime_result: '0-4',
        halftime_home_goal: 0,
        halftime_away_goal: 4,
      },
      {
        date: '2014-03-02',
        home_team_id: 8,
        away_team_id: 1,
        result: '6-5',
        home_goal: 6,
        away_goal: 5,
        season_id: 108,
        category: 'semi',
        group: 'S1',
        playoff: true,
        halftime_result: '4-2',
        halftime_home_goal: 4,
        halftime_away_goal: 2,
      },
      {
        date: '2014-03-03',
        home_team_id: 5,
        away_team_id: 2,
        result: '6-3',
        home_goal: 6,
        away_goal: 3,
        season_id: 108,
        category: 'semi',
        group: 'S1',
        playoff: true,
        halftime_result: '4-1',
        halftime_home_goal: 4,
        halftime_away_goal: 1,
      },
      {
        date: '2014-03-04',
        home_team_id: 1,
        away_team_id: 8,
        result: '4-5',
        home_goal: 4,
        away_goal: 5,
        season_id: 108,
        category: 'semi',
        group: 'S1',
        playoff: true,
        halftime_result: '2-2',
        halftime_home_goal: 2,
        halftime_away_goal: 2,
      },
      {
        date: '2014-03-05',
        home_team_id: 2,
        away_team_id: 5,
        result: '5-3',
        home_goal: 5,
        away_goal: 3,
        season_id: 108,
        category: 'semi',
        group: 'S1',
        playoff: true,
        halftime_result: '1-2',
        halftime_home_goal: 1,
        halftime_away_goal: 2,
      },
      {
        date: '2014-03-06',
        home_team_id: 8,
        away_team_id: 1,
        result: '8-7',
        home_goal: 8,
        away_goal: 7,
        season_id: 108,
        category: 'semi',
        group: 'S1',
        playoff: true,
        halftime_result: '4-5',
        halftime_home_goal: 4,
        halftime_away_goal: 5,
      },
      {
        date: '2014-03-08',
        home_team_id: 1,
        away_team_id: 8,
        result: '0-0',
        home_goal: 0,
        away_goal: 0,
        season_id: 108,
        category: 'semi',
        group: 'S1',
        playoff: true,
        halftime_result: '0-0',
        halftime_home_goal: 0,
        halftime_away_goal: 0,
      },
      {
        date: '2014-03-08',
        home_team_id: 5,
        away_team_id: 2,
        result: '6-5',
        home_goal: 6,
        away_goal: 5,
        season_id: 108,
        category: 'semi',
        group: 'S1',
        playoff: true,
        halftime_result: '1-2',
        halftime_home_goal: 1,
        halftime_away_goal: 2,
      },
      {
        date: '2014-03-10',
        home_team_id: 2,
        away_team_id: 5,
        result: '0-0',
        home_goal: 0,
        away_goal: 0,
        season_id: 108,
        category: 'semi',
        group: 'S1',
        playoff: true,
        halftime_result: '0-0',
        halftime_home_goal: 0,
        halftime_away_goal: 0,
      },
      {
        date: '2014-03-10',
        home_team_id: 8,
        away_team_id: 1,
        result: '0-0',
        home_goal: 0,
        away_goal: 0,
        season_id: 108,
        category: 'semi',
        group: 'S1',
        playoff: true,
        halftime_result: '0-0',
        halftime_home_goal: 0,
        halftime_away_goal: 0,
      },
      {
        date: '2014-03-16',
        home_team_id: 8,
        away_team_id: 5,
        result: '5-4',
        home_goal: 5,
        away_goal: 4,
        season_id: 108,
        category: 'final',
        group: 'final',
        playoff: true,
        halftime_result: '2-1',
        halftime_home_goal: 2,
        halftime_away_goal: 1,
      },
      {
        date: '2014-02-26',
        home_team_id: 22,
        away_team_id: 14,
        result: '2-6',
        home_goal: 2,
        away_goal: 6,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '1-1',
        halftime_home_goal: 1,
        halftime_away_goal: 1,
      },
      {
        date: '2014-02-26',
        home_team_id: 20,
        away_team_id: 4,
        result: '2-9',
        home_goal: 2,
        away_goal: 9,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '0-2',
        halftime_home_goal: 0,
        halftime_away_goal: 2,
      },
      {
        date: '2014-02-28',
        home_team_id: 14,
        away_team_id: 20,
        result: '4-3',
        home_goal: 4,
        away_goal: 3,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '2-2',
        halftime_home_goal: 2,
        halftime_away_goal: 2,
      },
      {
        date: '2014-02-28',
        home_team_id: 4,
        away_team_id: 22,
        result: '13-0',
        home_goal: 13,
        away_goal: 0,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '7-0',
        halftime_home_goal: 7,
        halftime_away_goal: 0,
      },
      {
        date: '2014-03-02',
        home_team_id: 22,
        away_team_id: 20,
        result: '2-8',
        home_goal: 2,
        away_goal: 8,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '0-6',
        halftime_home_goal: 0,
        halftime_away_goal: 6,
      },
      {
        date: '2014-03-02',
        home_team_id: 4,
        away_team_id: 14,
        result: '1-1',
        home_goal: 1,
        away_goal: 1,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '1-1',
        halftime_home_goal: 1,
        halftime_away_goal: 1,
      },
      {
        date: '2014-03-05',
        home_team_id: 20,
        away_team_id: 22,
        result: '7-2',
        home_goal: 7,
        away_goal: 2,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '2-2',
        halftime_home_goal: 2,
        halftime_away_goal: 2,
      },
      {
        date: '2014-03-05',
        home_team_id: 14,
        away_team_id: 4,
        result: '2-6',
        home_goal: 2,
        away_goal: 6,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '1-3',
        halftime_home_goal: 1,
        halftime_away_goal: 3,
      },
      {
        date: '2014-03-07',
        home_team_id: 22,
        away_team_id: 4,
        result: '2-5',
        home_goal: 2,
        away_goal: 5,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '1-3',
        halftime_home_goal: 1,
        halftime_away_goal: 3,
      },
      {
        date: '2014-03-07',
        home_team_id: 20,
        away_team_id: 14,
        result: '5-5',
        home_goal: 5,
        away_goal: 5,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '0-2',
        halftime_home_goal: 0,
        halftime_away_goal: 2,
      },
      {
        date: '2014-03-09',
        home_team_id: 4,
        away_team_id: 20,
        result: '4-3',
        home_goal: 4,
        away_goal: 3,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '2-2',
        halftime_home_goal: 2,
        halftime_away_goal: 2,
      },
      {
        date: '2014-03-09',
        home_team_id: 14,
        away_team_id: 22,
        result: '1-3',
        home_goal: 1,
        away_goal: 3,
        season_id: 108,
        category: 'qualification',
        group: 'KvalA',
        playoff: false,
        halftime_result: '0-2',
        halftime_home_goal: 0,
        halftime_away_goal: 2,
      },
      {
        date: '2014-02-26',
        home_team_id: 23,
        away_team_id: 10,
        result: '3-3',
        home_goal: 3,
        away_goal: 3,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '1-2',
        halftime_home_goal: 1,
        halftime_away_goal: 2,
      },
      {
        date: '2014-02-26',
        home_team_id: 17,
        away_team_id: 7,
        result: '2-5',
        home_goal: 2,
        away_goal: 5,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '1-3',
        halftime_home_goal: 1,
        halftime_away_goal: 3,
      },
      {
        date: '2014-02-28',
        home_team_id: 10,
        away_team_id: 17,
        result: '7-6',
        home_goal: 7,
        away_goal: 6,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '4-2',
        halftime_home_goal: 4,
        halftime_away_goal: 2,
      },
      {
        date: '2014-02-28',
        home_team_id: 7,
        away_team_id: 23,
        result: '8-6',
        home_goal: 8,
        away_goal: 6,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '3-1',
        halftime_home_goal: 3,
        halftime_away_goal: 1,
      },
      {
        date: '2014-03-02',
        home_team_id: 7,
        away_team_id: 10,
        result: '2-3',
        home_goal: 2,
        away_goal: 3,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '0-2',
        halftime_home_goal: 0,
        halftime_away_goal: 2,
      },
      {
        date: '2014-03-02',
        home_team_id: 23,
        away_team_id: 17,
        result: '5-0',
        home_goal: 5,
        away_goal: 0,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '2-0',
        halftime_home_goal: 2,
        halftime_away_goal: 0,
      },
      {
        date: '2014-03-05',
        home_team_id: 10,
        away_team_id: 7,
        result: '3-3',
        home_goal: 3,
        away_goal: 3,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '3-2',
        halftime_home_goal: 3,
        halftime_away_goal: 2,
      },
      {
        date: '2014-03-05',
        home_team_id: 17,
        away_team_id: 23,
        result: '4-3',
        home_goal: 4,
        away_goal: 3,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '4-1',
        halftime_home_goal: 4,
        halftime_away_goal: 1,
      },
      {
        date: '2014-03-07',
        home_team_id: 23,
        away_team_id: 7,
        result: '3-7',
        home_goal: 3,
        away_goal: 7,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '2-3',
        halftime_home_goal: 2,
        halftime_away_goal: 3,
      },
      {
        date: '2014-03-07',
        home_team_id: 17,
        away_team_id: 10,
        result: '1-2',
        home_goal: 1,
        away_goal: 2,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '0-1',
        halftime_home_goal: 0,
        halftime_away_goal: 1,
      },
      {
        date: '2014-03-09',
        home_team_id: 10,
        away_team_id: 23,
        result: '3-7',
        home_goal: 3,
        away_goal: 7,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '2-3',
        halftime_home_goal: 2,
        halftime_away_goal: 3,
      },
      {
        date: '2014-03-09',
        home_team_id: 7,
        away_team_id: 17,
        result: '7-4',
        home_goal: 7,
        away_goal: 4,
        season_id: 108,
        category: 'qualification',
        group: 'KvalB',
        playoff: false,
        halftime_result: '3-1',
        halftime_home_goal: 3,
        halftime_away_goal: 1,
      },
    ])
  },
  down: async ({ context: queryInterface }) => {
    await queryInterface.bulkDelete('games')
  },
}
