module.exports = {
  up: async ({ context: queryInterface }) => {
    await queryInterface.bulkInsert('tables', [
      {
        position: 1,
        team_id: 2,
        games: 26,
        won: 21,
        draw: 3,
        lost: 2,
        scored_goals: 149,
        conceded_goals: 85,
        goal_difference: 64,
        points: 45,
        season_id: 108,
      },
      {
        position: 2,
        team_id: 8,
        games: 26,
        won: 20,
        draw: 3,
        lost: 3,
        scored_goals: 192,
        conceded_goals: 100,
        goal_difference: 92,
        points: 43,
        season_id: 108,
      },
      {
        position: 3,
        team_id: 1,
        games: 26,
        won: 18,
        draw: 4,
        lost: 4,
        scored_goals: 156,
        conceded_goals: 97,
        goal_difference: 59,
        points: 40,
        season_id: 108,
      },
      {
        position: 4,
        team_id: 5,
        games: 26,
        won: 16,
        draw: 2,
        lost: 8,
        scored_goals: 132,
        conceded_goals: 92,
        goal_difference: 40,
        points: 34,
        season_id: 108,
      },
      {
        position: 5,
        team_id: 6,
        games: 26,
        won: 15,
        draw: 4,
        lost: 7,
        scored_goals: 142,
        conceded_goals: 116,
        goal_difference: 26,
        points: 34,
        season_id: 108,
      },
      {
        position: 6,
        team_id: 9,
        games: 26,
        won: 13,
        draw: 5,
        lost: 8,
        scored_goals: 133,
        conceded_goals: 96,
        goal_difference: 37,
        points: 31,
        season_id: 108,
      },
      {
        position: 7,
        team_id: 13,
        games: 26,
        won: 12,
        draw: 5,
        lost: 9,
        scored_goals: 117,
        conceded_goals: 113,
        goal_difference: 4,
        points: 29,
        season_id: 108,
      },
      {
        position: 8,
        team_id: 12,
        games: 26,
        won: 9,
        draw: 4,
        lost: 13,
        scored_goals: 119,
        conceded_goals: 126,
        goal_difference: -7,
        points: 22,
        season_id: 108,
      },
      {
        position: 9,
        team_id: 15,
        games: 26,
        won: 7,
        draw: 4,
        lost: 15,
        scored_goals: 96,
        conceded_goals: 122,
        goal_difference: -26,
        points: 18,
        season_id: 108,
      },
      {
        position: 10,
        team_id: 11,
        games: 26,
        won: 5,
        draw: 7,
        lost: 14,
        scored_goals: 89,
        conceded_goals: 113,
        goal_difference: -24,
        points: 17,
        season_id: 108,
      },
      {
        position: 11,
        team_id: 4,
        games: 26,
        won: 6,
        draw: 3,
        lost: 17,
        scored_goals: 80,
        conceded_goals: 104,
        goal_difference: -24,
        points: 15,
        season_id: 108,
      },
      {
        position: 12,
        team_id: 7,
        games: 26,
        won: 4,
        draw: 5,
        lost: 17,
        scored_goals: 74,
        conceded_goals: 126,
        goal_difference: -52,
        points: 13,
        season_id: 108,
      },
      {
        position: 13,
        team_id: 10,
        games: 26,
        won: 4,
        draw: 5,
        lost: 17,
        scored_goals: 72,
        conceded_goals: 160,
        goal_difference: -88,
        points: 13,
        season_id: 108,
      },
      {
        position: 14,
        team_id: 14,
        games: 26,
        won: 3,
        draw: 4,
        lost: 19,
        scored_goals: 52,
        conceded_goals: 153,
        goal_difference: -101,
        points: 10,
        season_id: 108,
      },
    ])
  },
  down: async ({ context: queryInterface }) => {
    await queryInterface.bulkDelete('tables')
  },
}
