export const groupConstant = {
  S1: 'Semifinal 1',
  S2: 'Semifinal 2',
  Q1: 'Kvartsfinal 1',
  Q2: 'Kvartsfinal 2',
  Q3: 'Kvartsfinal 3',
  Q4: 'Kvartsfinal 4',
  E1: 'Åttondelsfinal 1',
  E2: 'Åttondelsfinal 2',
  E3: 'Åttondelsfinal 3',
  E4: 'Åttondelsfinal 4',
  elitserien: 'Elitserien',
  ElitA: 'Elit A',
  ElitB: 'Elit B',
  KvalA: 'Kvalgrupp A',
  KvalB: 'Kvalgrupp B',
  allsvenskan: 'Allsvenskan',
  AllsvNorr: 'Allsvenskan Norra',
  AllsvSyd: 'Allsvenskan Södra',
  Div1Syd: 'Division 1 Södra',
  Div1Norr: 'Division 1 Norra',
  Div1Central: 'Division 1 Central',
  Div1NorrA: 'Division 1 Norra A',
  Div1NorrB: 'Division 1 Norra B',
  Div1SydA: 'Division 1 Södra A',
  Div1SydB: 'Division 1 Södra B',
  NedflyttningNorr: 'Norra nedflyttningsgruppen',
  NedflyttningSyd: 'Södra nedflyttningsgruppen',
  AvdA: 'Avdelning A',
  AvdB: 'Avdelning B',
  AvdC: 'Avdelning C',
  AvdD: 'Avdelning D',
}
