name: Health Check Bandyresultat

on:
  schedule:
     - cron: '0 * * * *'
  
  push:
    branches:
      - main
jobs:
  Health-check-bandyresultat:
    runs-on: ubuntu-latest
    steps:
      - name: Health Check Bandyresultat
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://bandyresultat.se/api/healthCheck
          max-attempts: 3
          retry-delay: 5s
